### ISSUE TITLE
Clarification request: 32-bit ISO for MK6 or Boxor hardware?

### ISSUE THREAD

**Issue by quietly-turning** [sherl0k/InstallTheGroove#3]
The README currently states:

```
and a 32-bit ISO for the original BoXoR hardware
```

Though absolute definitions are hard to find on the internet, my understanding (from @vyhd) is that:
- ITG2 dedicabs contained **Andamiro MK6 units** (effectively the same PCs found in PIU GX cabinets)
- ITG/2 upgrades kits for retrofitting DDR cabinets were sold as **Boxor units**.

I'm admittedly unfamiliar with the hardware in upgrade kits.  I understand that they used a JAMMA-->USB card referred to as an ITGIO, which was completely distinct from Andamiro's typical PIUIO card (which is only JAMMA in appearance and doesn't actually comply with JAMMA wiring standards).

Anyway, I suspect you mean to say that the 32-bit ISO has been prepared for original Andamiro MK6 units (but maybe you do actually mean Boxor).  I felt it was worth requesting clarification.

Thank you for putting this package together.  I am all for progress. :)

**Comment by sherl0k** [comment]
Both kits run on 32-bit processors, so I suppose the naming convention (BoXoR vs MK6) is moot. Even so, I'll update the readme to clarify.

**Comment by quietly-turning** [comment]
Thank you!
